name: Android Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - github-actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.5"
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      # - name: Analyze project
      #   run: flutter analyze

      - name: Build APK
        run: flutter build apk --release

      - name: Build AppBundle
        run: flutter build appbundle --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: offlinesvet-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload AppBundle
        uses: actions/upload-artifact@v4
        with:
          name: offlinesvet-aab
          path: build/app/outputs/bundle/release/app-release.aab