name: iOS Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - github-actions

permissions:
  contents: read

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.5"
          channel: stable
          cache: true

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Show Flutter Version
        run: flutter --version

      - name: Check iOS Project
        run: |
          ls -la ios
          ls -la ios/Runner
          ls -la ios/Flutter

      - name: Build iOS (No Code Sign)
        run: flutter build ios --release --no-codesign

      - name: Create Payload
        run: |
          mkdir Payload
          cp -R build/ios/iphoneos/Runner.app Payload/

      - name: Create IPA
        run: |
          zip -r offlinesvet.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: offlinesvet-ipa
          path: offlinesvet.ipa